# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEyRNyk-y2pEskdR7KhHvFB7Fq7eVsb5
"""

import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv('USArrests.csv')
data.head(5)

data.index

data.index=data.iloc[:, 0]
data.index

data.index=data.iloc[:, 0]
data.index

data.head()

data=data.iloc[:, 1:5]
data.head()

data.index.name=None
data.head()

data.isnull().sum()

data.info()

Murder=data['Murder']
Murder.info()

Assault=data['Assault']
Assault.info()

UrbanPop=data['UrbanPop']
UrbanPop.info()

Rape=data['Rape']
Rape.info()

plt.scatter('Murder','Assault','Rape',data=data)
plt.show()

from sklearn.cluster import KMeans
k_score_list=[]
for x in range (1,15):
  kmeans=KMeans(n_clusters=x)
  kmeans.fit(data)
  k_score_list.append(kmeans.inertia_)

plt.plot(range(1,15),k_score_list)
plt.xlabel(" K Değeri")
plt.ylabel("WCSS")
plt.show()

kmeans1=KMeans(n_clusters=3)
clusters=kmeans1.fit_predict(data)

clusters

data["label"]=clusters
data.head()

from mpl_toolkits.mplot3d import Axes3D

kmeans1=KMeans(n_clusters=3)
model=kmeans1.fit(data)
clusters=model.labels_
merkez=kmeans.cluster_centers_

plt.rcParams['figure.figsize']=(16,9)
fig=plt.figure()
ax=Axes3D(fig)
ax.scatter(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2])

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans


# K-Means kümeleme
kmeans1 = KMeans(n_clusters=3)
model = kmeans1.fit(data)
clusters = model.labels_
centroids = kmeans1.cluster_centers_

# Grafik oluştur
plt.rcParams['figure.figsize'] = (16, 9)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Veri noktalarını çiz
ax.scatter(data.iloc[:, 0], data.iloc[:, 1], data.iloc[:, 2],
           c=clusters, cmap='viridis', s=50)

# Küme merkezlerini çiz
ax.scatter(centroids[:, 0], centroids[:, 1], centroids[:, 2],
           c='red', s=200, marker='X', label='Cluster Centers')

# Eksen etiketleri
ax.set_xlabel('X Axis')
ax.set_ylabel('Y Axis')
ax.set_zlabel('Z Axis')

# Başlık ve gösterim
ax.set_title('3D K-Means Clustering')
plt.legend()
plt.show()

fig=plt.figure()
ax=Axes3D(fig)
ax.scatter(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2], c=clusters)
ax.scatter(merkez[:,0],merkez[:,1],merkez[:,2],c='red')